version: '3.2'

volumes:
  tmp-data:
  redis-data:

services:
  app:
    image: golang:1.13-stretch
    working_dir: /moscow-taxi-parking
    environment:
      HOME: /tmp
      GOPATH: /tmp
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - .:/src:cached
      - tmp-data:/tmp:cached
    depends_on:
      - redis

  redis:
    image: redis:5.0.7
    volumes:
      - redis-data:/data:cached
    ports:
      - 6379
      - '6379:6379'