version: '2.2'

volumes:
  tmp-data:
  redis-data:

services:
  app:
    image: golang:1.12-stretch
    network_mode: host
    environment:
      - DB_CONN=localhost:6379
      - SRC_URL=https://data.gov.ru/opendata/7704786030-taxiparking/data-20190906T0100.json?encoding=UTF-8
    working_dir: /moscow-taxi-parking/
    volumes:
      - ./:/moscow-taxi-parking/
    command: bash -c "go test -v -cover -timeout 30s ./... "
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:5.0.7
    network_mode: host
    volumes:
      - redis-data:/data:cached
    expose:
      - "6379"
    ports:
      - "6379:6379"
    healthcheck:
      test: "redis-cli ping |grep PONG"
      interval: 3s
      timeout: 20s
      retries: 10
