version: '2.2'

services:
  db:
    image: redis:5.0.7
    network_mode: host
    ports:
      - "6379:6379"
    healthcheck:
      test: "redis-cli ping |grep PONG"
      interval: 3s
      timeout: 20s
      retries: 10
